### ISSUE TITLE
能不能实现展示端播放结果回调Server端

### ISSUE THREAD

**Issue by wellcao** [huzongyao/PlatinumMedia#6]
就是MediaSource控制MediaRender端，实现了播放暂停音量等，缺一半展示端VideoView的手势操作需要回传给MediaSource端显示，比如VideoView点击了暂停，source端也应该被暂停。

**Comment by huzongyao** [comment]
只有一个server，所以调用只能从client->server，要实现回调的化可以让client定时轮询实现

**Comment by wellcao** [comment]
> 只有一个server，所以调用只能从client->server，要实现回调的化可以让client定时轮询实现

老哥，我理解的是DMR还需要实现DMC的功能，就是DMR这边可以控制QQ音乐的播放和暂停。像windows的WindowsMediaPlayer，可以使用它接收腾讯视频，另外它能控制QQ音乐的播放暂停。我运行的这个项目是只有展示没有控制功能的。

**Comment by huzongyao** [comment]
这个估计先要找一些可以实现这个功能的DMR竞品抓一下协议看看是怎么实现的，我想到的方法就是DMC不断轮询DMR，来获取DMR上的播放状态，音量等信息，这样就实现DMR传递信息给DMC

**Comment by wellcao** [comment]
![Uploading 快照30.png…]()
这是我使用cling框架的server端抓到的WindowsMediaPlayer的action，就是windowsMediaPlayer作为ControlPoint发送的action啊
